# Generated by Django 4.2.1 on 2023-07-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='college_name',
            new_name='collegename',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='roll_no',
            new_name='rollno',
        ),
    ]
