# Generated by Django 4.2.1 on 2023-07-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_college_name_login_collegename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='collegename',
        ),
        migrations.RemoveField(
            model_name='login',
            name='rollno',
        ),
    ]
